cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [ 
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ec_sample/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views


app_name = 'search'

urlpatterns = [
        path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

cart/models.py
from django.db import models
from shop.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=250, )
    slug = models.SlugField(max_length=250, )


    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
         return self.name



class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

    
    # name = models.CharField(max_length=250)
    # slug = models.SlugField(max_length=250)
    # description = models.TextField(blank=True)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # price = models.IntegerField()
    # image = models.ImageField(upload_to='product', blank=True)
    # stock = models.IntegerField()
    # available = models.BooleanField(default=True)

cart/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
import stripe



def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def cart_detail(request, total=0, counter=0, cart_items = None):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart, active=True)
    for cart_item in cart_items:
        total += (cart_item.product.price * cart_item.quantity)
        counter += cart_item.quantity
    # stripe
    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)
    description = 'Perfect Cushion Shop - New Order'
    data_key = settings.STRIPE_PUBLIC_KEY
    if request.method == 'POST':
        print(request.POST)
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            customer = stripe.Customer.create(
                        email=email,
                        source=token
             )
            charge = stripe.Charge.create(
                       amount=stripe_total,
                       currency='jpy',
                       description=description,
                       customer=customer.id
              )
        except stripe.error.CardError as e:
            return False,e

    return render(request, 'cart.html', {'cart_items':cart_items, 'total':total, 'counter':counter, 'data_key':data_key, 'stripe_total':stripe_total, 'description':description})

# def add_cart(request, product_id):
#     product = Product.objects.get(id=product_id)
#     cart = Cart.objects.get(cart_id=_cart_id(request))
#     cart_item = CartItem.objects.get(product=product, cart=cart)
#     if cart_item.quantity < cart_item.product.stock:
#         cart_item.quantity += 1
#         cart_item.save()
#     return redirect('cart:cart_detail')

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
                cart_id =  _cart_id(request)
            )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart,product=product)  
    cart_item.delete()
    return redirect('cart:cart_detail')

search/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage



def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page)
    else:
        products_list = Product.objects.all()

    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pags)

    return render(request, 'shop/category.html', {'category': c_page, 'products': products})



def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product': product})

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    {% if not cart_items %}
          <div class="text-center">
            <br>
            <h1 class="text center my_title">Your shopping cart is empty</h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'shop:allProdCat' %}">here</a> to continue shopping.
            </p>
          </div>
    {% else %}
            <div class="text-center">
                <br>
                <h1 class="text-center my_title my-4">
                    Your shopping cart
                </h1>
            </div>
            <br>
            
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                            <th colspan="5">
                            Your items
                            <br>
                            <br>
                                </th>
                            </tr>
                        </thead> 
                    <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td><a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a></td>
                            <td class="text-left">
                               {{cart_item.product.name}}  
                                <br>
                                ¥{{cart_item.product.price}}
                                <br>
                                 {{cart_item.quantity}}個
                            </td>
                            <td> ¥{{cart_item.sub_total}} </td>
                            
                            {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                        <i class="fas fa-plus-circle custom_icon"></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fas fa-minus-circle custom_icon"></i>
                                     </a>
                                    &nbsp;
                                   
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_item">
                                    <i class="far fa-trash-alt"></i> 
                                    </a>
                                </td>
                            {% else %}
                                <td>
                                    &nbsp;
                                    <a href="" class="custom_a">
                                        <i class="fas fa-minus-circle custom_icon"></i>
                                    </a>
                                    &nbsp;
                                    <a href="" class="custom_item">
                                        <i class="far fa-trash-alt"></i> 
                                    </a>
                                </td>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-12 col-sm-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                  <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                            <br>
                            <br>
                        </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                        <td class="text-left">
                            Your total :  <strong>¥{{ total }}</strong>
                        </td>
                    </tr>
                  </tbody>
                </table>
                <br>
                
                <div class="mx-auto">
                        <form action="" method="POST">
                        {% csrf_token %}
                            <script
                        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="{{ data_key }}"
                        data-amount="{{ data_total }}"
                        data-name="Perfect Cushion Shop"
                        data-description=" description "
                        data-image="{% static 'img/logo.png' %}"
                        data-locale="auto"
                        data-currency="jpy"
                        data-shipping-address="true"
                        data-bulling-address="true"
                        data-zip-code="true">
                        </script>
                        </form>

                    <br>    
                    <br>
                        <a href="{% url 'shop:allProdCat' %}"> <p class="continue">Continue Shopping</p> </a>
                </div>
        </div>
    {% endif %}
{% endblock %}

search/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
    <div>
        <p class="text-center my_search_text my-5 ">You have searchd for: <b>"{{ query }}"</b></p>
    </div>
    
    <div class="container">
        <div class="row mx-auto">
            {% for product in products  %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center my-4" style="min-width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image mt-4" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>£{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found.</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&display=swap" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">

    <title>No Name</title>
  </head>

<body>
     
        {% include 'shop/navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'shop/footer.html' %}




     <!-- Optional JavaScript; choose one of the two! -->
    <script  src="/static/js/main.js"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
</body>
</html>

shop/templates/shop/category.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    {% if category %}
        <div class="row my_row_class ">
          <div class="mx-auto">
              <p><a href="{% url 'shop:allProdCat' %}"> Product </a> | {{category.name}}</p>
          </div>
        </div>
    {% endif %}
    {% if category %}
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
    </div>
    {% else %}
    <div>
        <h1 class="text-center my_title my-5">All Products</h1>
    </div>
    {% endif %}

    <div class="container">
        <div class="row mx-auto ">
            {% for product in products.object_list  %}
            <div class=" col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center my-4" >
                    <a href="{{product.get_url}}"><img class="card-img-top my_image mt-4" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>¥{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="mx-auto text-center ">
            {% if products.paginator.num_pages > 1 %}
              <hr>
              <div class="text-cente">
                  {% for pg in products.paginator.page_range %}
                  <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
                  {% endfor %}
              </div>
            {% endif %}
        </div>
        <br>


    </div>
{% endblock %}

shop/templates/shop/footer.html
<footer >

  <div class="footer-container mx-auto text-black  ">
       <p class="copyright mt-4 ">
       © 2021 No Name
       </p> 
 
    
 </div>

</footer>

shop/templates/shop/login.html
{% extends 'base.html' %}


{% block content %}


<div class="container">

    <form class="form-signin" method="post"   {% csrf_token %} >
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign up</h1>
    <label for="inputEmail" class="visually-hidden">username</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="username" required="" autofocus="">
    <label for="inputPassword" class="visually-hidden">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">© 2017–2021</p>
  </form>

</div>



  {%  endblock %}

shop/templates/shop/navbar.html
<nav class="navbar  ">
  <ul class="d-flex">
      <li class="nav-item home"><a class="home_a" href="{% url 'shop:allProdCat' %}">Home</a> </li>

      {% if item_count > 0 %}
      <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart">({{item_count}})</i></a>
     </li>
     {% endif %}

  <form class="my-lg-0 ml-auto  d-flex"  action="{% url 'search:searchResult' %}" method="get">
        {% csrf_token %}
      <input class="form-control mr-sm-2 " type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0 " type="submit"><i class="fas fa-search"></i></button>
    </form>
    
    </ul>
  
</div>

</nav>

shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="row my_prod_row_class">
  <div class="mx-auto w-75 mt-4 product ">
      <p class=""></p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> - {{product.name}}</p>
      </div>

          <div class="row my-5">
              <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                  <div style="min-width: 18rem">
                      <img class="product-img" src="{{product.image.url}}" alt="{{product.name}}">
                  </div>
              </div>
              <div class="col-12 col-sm-12 col-md-12 col-lg-6 my-4">
                  <div>
                      <h1 class="my_prod_title">{{product.name}}</h1>
                      <p class="my_prod_price">¥{{product.price}}</p>
                      <p class="my_prod_text">{{product.description}}</p>
                      {% if product.stock <= 0 %}
                      <p class="my_prod_text"><b>Out of Stock</b></p>
                      {% else %}
                      <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                      {% endif %}
                  </div>
              </div>
          </div>
    </div>
</div>

{% endblock %}